version: '3.8'

services:
    dev_api:
        container_name: prova_nwsys_api
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: yarn start:dev
        ports:
            - 3000:3000
        networks:
            - nestjs-network
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        container_name: prova_nwsys_postgres
        image: postgres:14.2-alpine
        environment:
            POSTGRES_USER: jlucaso
            POSTGRES_PASSWORD: senhaforte
            POSTGRES_DB: prova_nwsys
        networks:
            - nestjs-network
        restart: always

networks:
    nestjs-network:

volumes:
  node_modules: {}